export const GET_WORKSHOPS_REQUEST = 'GET_WORKSHOPS_REQUEST';
export const GET_WORKSHOPS_SUCCESS = 'GET_WORKSHOPS_SUCCES';
export const GET_WORKSHOPS_FAILURE = 'GET_WORKSHOPS_FAILURE';
export const GET_FILTERED_WORKSHOPS = 'GET_FILTERED_WORKSHOPS';

export const APPLY_FILTER = 'APPLY_FILTER';
