// workshops types
export const GET_WORKSHOPS_REQUEST = 'GET_WORKSHOPS_REQUEST';
export const GET_WORKSHOPS_SUCCESS = 'GET_WORKSHOPS_SUCCESS';
export const GET_WORKSHOPS_FAILURE = 'GET_WORKSHOPS_FAILURE';
export const GET_FILTERED_WORKSHOPS = 'GET_FILTERED_WORKSHOPS';
export const GET_SIMILAR_WORKSHOPS = 'GET_SIMILAR_WORKSHOPS';

// users types
export const GET_WORKSHOP_USER_REQUEST = 'GET_WORKSHOP_USER_REQUEST';
export const GET_WORKSHOP_USER_SUCCESS = 'GET_WORKSHOP_USER_SUCCESS';
export const GET_WORKSHOP_USER_FAILURE = 'GET_WORKSHOP_USER_FAILURE';

// filters types
export const APPLY_FILTER = 'APPLY_FILTER';
